// angular-frontend/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';

import { FeedService } from './service/feed.service';
import { FeedItem } from './model/feed.model';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  articles?: any;

  constructor(private feedService: FeedService) {}

  getArticles(): void {
    this.feedService.getAllFeeds().subscribe({
      next: (data) => {
        const stringifiedData = JSON.stringify(data);
        this.articles = JSON.parse(stringifiedData);
      },
      error: (e) => console.error(e),
    });
  }

  ngOnInit(): void {
    this.getArticles();
  }
  title = 'rss-feed';
}

<div>
  <h1 class="text-xl text-center font-semibold mt-6">
    RSS Feed From Tech Crunch
  </h1>
  <hr class="mt-2 mb-4" />
  <div class="w-3/4 max-w-lg border mx-auto p-6 rounded-xl">
    <!-- Tech Crunch Logo -->
    <div
      class="bg-orange-50 felx flex-col items-center rounded-lg py-6 px-4 mb-5"
    >
      <img
        src="
       https://i.piano.io/managedservices/techCrunch/techcrunch-plus-logo--green.svg"
        alt="tech crunch rss feed"
      />
    </div>
    <div *ngFor="let article of articles; let i = index">
      <app-feed
        [title]="article.item.title"
        [link]="article.item.link"
        [date]="article.item.pubDate"
      ></app-feed>
    </div>
  </div>
  <!-- end of the feed list -->
</div>

// react-frontend/src/App.jsx
import Axios from "axios";
import { useEffect, useState } from "react";
import Feed from "./Feed";

function App() {
  const [articles, setArticles] = useState([]);

  const getArticles = async () => {
    try {
      const res = await Axios.get("http://localhost:5000");
      setArticles(res.data);
    } catch (error) {
      console.log(error);
    }
  }; // end getArticles

  useEffect(() => {
    getArticles();
  }, []);

  return (
    <div>
      <h1 className="text-xl text-center font-semibold mt-6">
        RSS Feed From Tech Crunch
      </h1>
      <hr className="mt-2 mb-4" />
      <div className="w-3/4 max-w-lg border mx-auto p-6 rounded-xl">
        {/* Tech Crunch Logo */}
        <div
          className="bg-orange-50 felx flex-col items-center rounded-lg py-6
        px-4 mb-5"
        >
          <img
            src="
          https://i.piano.io/managedservices/techCrunch/techcrunch-plus-logo--green.svg"
            alt="tech crunch rss feed"
          />
        </div>

        {articles.map((article, i) => (
          <Feed
            key={i}
            title={article.item.title}
            link={article.item.link}
            date={article.item.pubDate}
          />
        ))}
      </div>
    </div>
  );
}

export default App;
