// react-frontend/src/Feed.jsx
import React from "react";

const Feed = ({ title, link, date }) => {
  const dateFormat = { month: "long", day: "numeric", year: "numeric" };
  let articleDate = new Date(date).toLocaleDateString("en-US", dateFormat);
  return (
    <div className="max-w-lg rounded overflow-hidden shadow-lg my-5 p-3">
      <a
        href={link}
        target="_blank"
        className="hover: opacity-70 hover:text-blue-300"
      >
        <h3 className="text-xl mb-2 underline ">{title}</h3>
        <p>{articleDate}</p>
      </a>
    </div>
  );
};

export default Feed;

// angular-frontend/src/app/feed/feed.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-feed',
  templateUrl: './feed.component.html',
  styleUrls: ['./feed.component.css'],
})
export class FeedComponent {
  @Input() title: string = '';
  @Input() link: string = '';
  @Input() date: string = '';

  constructor() {}

  get articleDate() {
    // const dateFormat = { month: 'long', day: 'numeric', year: 'numeric' };
    return new Date(this.date);
  }
}

<div class="max-w-lg rounded overflow-hidden shadow-lg my-5 p-3">
  <a
    [href]="link"
    target="_blank"
    class="hover: opacity-70 hover:text-blue-300"
  >
    <h3 class="text-xl mb-2 underline">{{ title }}</h3>
    <p>{{ articleDate }}</p>
  </a>
</div>
